source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!



target :SSPhotoKit_Example do
  pod 'ImagePickerSheetController'
  pod 'SSImageBrowser'
  pod 'AsyncDisplayKit'
end
